### PR TITLE
Fix the asks function

### LINKED ISSUE #130: Modify the definition of the `asks` function of `ComonadEnv`.
The current definition is more restrictive than necessary. Modify as follows.

from
`asks :: forall e1 e2 w. ComonadEnv e1 w => (e1 -> e2) -> w e1 -> e2`
to
`asks :: forall e1 e2 w a. ComonadEnv e1 w => (e1 -> e2) -> w a -> e2`

The Haskell definition is as follows.
`asks :: ComonadEnv e w => (e -> e') -> w a -> e'`

### PR DESCRIPTION
**Pull request by mutex-w**
Thank you for your response to Issue! &#x1f600;
I've made some modifications based on #130.
This is a change to the type definition only.
The constraints are loosened and compatibility with existing sources will be maintained.
Closes #130

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]
I would be tempted to release this as a breaking change because it’s possible that someone is relying on the more restricted current type signature for type inference to work. It is quite unlikely, admittedly.

**Comment by garyb** [comment]
I can't really think of a way this would break an existing inferred type 🤔. Are we going to be breaking this library for 0.14 anyway though? If so, then I guess waiting makes sense.

**Comment by hdgarrood** [comment]
Here's an example: https://try.purescript.org/?gist=a4db03ecd5e0385e28c493d29f83a686&session=ea0ea2de-a087-ad4b-ec4b-b096e3d090d9

**Comment by thomashoneyman** [comment]
Merging as part of upcoming 0.14 changes.

**Pull request merged**
