### PR TITLE
Topic/rwst monad rec

### PR DESCRIPTION
**Pull request by ethul**
I thought it might be easier to discuss in a PR.

I've added a simple benchmark test. For the current value (10000) it takes about 340 milliseconds to run on my machine.

What do you think about the performance?

### CODE REVIEW

**Comment by paf31** [comment]
Can we compare to `State`, for example?

I think we could probably speed things up by replacing `See` with an ADT, but it would be a breaking change.

**Comment by ethul** [comment]
I am testing against `State`. For 1,000,000 iterations `RWST` is at about 30 seconds running time. And state is at 7.5 seconds running time.

The ADT may speed things up. Do you think it is the object creation that is slow?

Using [node-inspector](https://github.com/node-inspector/node-inspector) I can see that `mkSee` is the heaviest in a CPU profile.

I can try some options to see if we can get it faster.

**Comment by ethul** [comment]
I am wondering if it is the four-level curried function generated for `mkSee` or just the object creation itself.

**Comment by ethul** [comment]
I've updated to using an ADT as you suggest. Much faster.

For 1,000,000:
- RWST => 3.9 seconds
- StateT => 1.6 seconds

**Comment by ethul** [comment]
Also, would you prefer I export the `See` constructor or have a `runSee` or something to get at the values. The values cannot be accessed at the moment (oops...)

**Comment by paf31** [comment]
What's the alternative? A record?

**Comment by ethul** [comment]
I suppose so. Exporting the constructor might be the easiest. But let me know what you think is best.

**Comment by paf31** [comment]
Well, it "breaks encapsulation" I guess, but for performance I think we need to export `See` if users want to use the underlying API.

Another point: should `See` be renamed? I never really understood that name. Is `RWSResult` any better, for example?

**Comment by ethul** [comment]
I agree on exporting. Also I think `RWSResult` works. I was trying to think of something shorter. Something like `Triple`. But it might be best to have the `RWS` in there. Should we go with `RWSResult`?

**Comment by paf31** [comment]
I'm fine with that, but maybe someone else has a better idea. We could leave this for a day and see.

**Comment by ethul** [comment]
I've made the change. We can definitely leave it for a few days to see if something better surfaces. Otherwise it should be ready to go.

**Comment by garyb** [comment]
It was named `See` as a joke I think, as the type variables were `s a w`.

**Comment by garyb** [comment]
Bump? I'm happy to merge, we can always revisit later if it's deemed too inefficient and there's a better approach.

**Comment by paf31** [comment]
:+1:

**Pull request merged**
