### PR TITLE
add MonadThrow MonadError instances for Effect

### PR DESCRIPTION
**Pull request by safareli**

### CODE REVIEW

**Comment by safareli** [comment]
Great! (feel free to do squish merge, I was lazy and used web editor of github for this pr, hence this many commits :D)

**Comment by hdgarrood** [comment]
Wait, I thought our policy was that a dependency change is only considered breaking if a dependency is being removed (because you can pull things in via transitive dependencies and not mention them explicitly in your local bower.json file)?

**Comment by garyb** [comment]
Additions can hypothetically break too:

- A depends on B and C
- B depends on D v1
- C adds a dependency for D v2 and only minor-bumps
- Installing the most up to date dependencies for A would now fail

**Comment by hdgarrood** [comment]
Aren't solvers supposed to deal with situations like that - in this case, by taking the older version of C? (Admittedly Bower doesn't really have one...)

**Comment by garyb** [comment]
Yeah I guess so, but also yeah Bower doesn't solve :wink:

**Comment by safareli** [comment]
in this case tho, ps-exceptions v4 is published with ps@0.12 version so older version can't be used anyway (I guess)

**Pull request merged**
