### PR TITLE
Prepare for 2.0 release

### LINKED ISSUE #60: Apply and Applicative instance of ExceptT are inconsistent
- https://github.com/purescript/purescript-transformers/blob/v0.8.1/src/Control/Monad/Except/Trans.purs#L53-L60
- https://github.com/scalaz/scalaz/pull/255

### LINKED ISSUE #63: Proposal:Split MonadReader and MonadWriter
In `mtl` I've long wanted to split apart `MonadReader` and `MonadWriter` into two parts each. Splitting off the algebraic effects in each case yields a subclass that is much more often implementable.

```haskell
class MonadAsk e m | m -> e where
   ask :: m e

class MonadAsk e m => MonadReader e m | m -> e where
  local :: forall a. (e -> e) -> m a -> m a

class MonadTell w m | m -> w where
   tell :: w -> m ()

class MonadTell w m => MonadWriter w m | m -> w where
   listen :: forall a. m a -> m (Tuple a w)
   pass :: forall a. m (Tuple a (w -> w)) -> m a
```

Of course the fundeps there can't be written currently.

This has the benefit that a number of additional instances can exist for MonadAsk and MonadTell. 

Notably you can use MonadTell for things like logging in some IO-like monad. Or with something like `reflection` you can make:

```haskell
instance Refies s w => MonadAsk w (Tagged s) 
```

### LINKED ISSUE #72: ListT.scanl broken?
I didn't try it out, just "translated" it, but it looks like line 218 in https://github.com/purescript/purescript-transformers/blob/v1.0.0/src/Control/Monad/List/Trans.purs should read

`h (Yield a s) = let b'' = f b' a in Just $ Tuple (Tuple b'' (force s)) b''`

Note the use of `b'` instead of `b`, which make IMHO no sense in this context.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #72, resolves #63, resolves #60

Still to do:

- [x] Implement `MonadAsk` / `MonadTell` - #63 
- [x] Figure out what needs to happen with #60

### CODE REVIEW

**Comment by garyb** [comment]
I'll finish up tomorrow, unless anyone beats me to it.

**Comment by garyb** [comment]
As far as I can tell, `ExceptT` needs to have `Apply` implemented as `ap` so that the behaviour is consistent with `bind`, but this does mean that we have a `Monad m` constraint from `Apply` downwards now... but, I've just realised that the change I made to `MaybeT` to loosen the constraints suffers from the very problem I just fixed for `ExceptT`.

I'm not sure what to suggest, since it seems like this the right thing, since the difference is this: the `m` is run regardless of whether the value is `Nothing` / `Left` in the apply case, but not in the `Monad` case. Maybe there's some way to make `bind` behave the same as `apply` instead, but I'm not really sure what that means, and it might have negative consequences.

Without the looser constraints we can't have [`MonadPar` instances for `MaybeT`](https://github.com/purescript/purescript-parallel/pull/10/files#diff-29f4ae4b5ce7893cbd2dee94f4ed0c89R133) and now `ExceptT` it would seem, but then maybe that is correct, since they "don't work properly" in parallel?

**Comment by garyb** [comment]
Maybe the answer is to use the `Monad` constrained versions and provide custom applicative newtyped versions for `MonadPar`?

**Comment by paf31** [comment]
Does it make sense to break up `ComonadEnv` and `ComonadTraced` too? What are examples of monads which have `ask` but not `local` etc.?

**Comment by paf31** [comment]
Why not 

```purescript
apply (ExceptT f) (ExceptT x) = ExceptT (lift2 ($) <$> f <*> x)
```

?

Do you mean they're not equal in terms of what gets evaluated? True, but they're observationally equivalent, right?

**Comment by garyb** [comment]
That is how I changed apply for `MaybeT`, and how it was for `EitherT` - that exact implementation is what #60 complains about.

Honestly I have no idea, I stared at it for quite a long time trying to figure out whether the extra `m` running mattered or not.

**Comment by paf31** [comment]
What do you mean when you say the `m` is run?

**Comment by garyb** [comment]
I mean, with the apply version the effects occur for both sides regardless of whether the left fails or succeeds... right?

I was going to put something together to try and prove whether it matters or not, but haven't gotten around to it yet.

**Comment by garyb** [comment]
(Trying now)

**Comment by paf31** [comment]
A good test would be something like `forever` in the `MaybeT (Eff _)` monad, I think.

**Comment by paf31** [comment]
It sounds like there is an issue, but we can probably fix it with a `newtype`, either here (preferable) or in `parallel`, but I would _really_ like to be able to implement `MonadPar` for something related to `ExceptT` and `MaybeT`.

**Comment by garyb** [comment]
``` purescript
main :: Eff (console :: CONSOLE) Unit
main = do
  void $ runMaybeT $ f <*> a
  log "---"
  void $ runMaybeT $ ap f a

f :: forall a. MaybeT (Eff (console :: CONSOLE)) (a -> a)
f = do
  lift $ log "Hello"
  MaybeT $ pure Nothing

a :: MaybeT (Eff (console :: CONSOLE)) String
a = do
  lift $ log "LAUNCH THE MISSILES!"
  pure "foo"
```

```
Hello
LAUNCH THE MISSILES!
---
Hello
```

**Comment by garyb** [comment]
We can definitely define newtype(s) with the desired applicative behaviour, with the caveat that they'll behave in the above way. I think the example above settles the discussion over whether the `ap` approach is right or not here though, unfortunately.

**Comment by paf31** [comment]
Sounds good

**Comment by garyb** [comment]
I'd vote for putting those `newtype`s in `Parallel`, as they're probably not going to be that useful on the whole outside of that situation. Given that, I think this PR is done sans any further comments.

**Comment by paf31** [comment]
I'm fine with putting them in `parallel`. Can we add `ComonadTell` though? It will be necessary to break things up in my `pairings` and `day` libraries when I implement a `MonadTell` instance for `Co w`.

**Comment by garyb** [comment]
That's supposed to come out of `ComonadTraced` right? It might need some refactoring if so, as it's already only made up of one function: `track :: forall a. t -> w a -> a`.

**Comment by paf31** [comment]
Ah ok, interesting. Sounds good then.

**Pull request merged**
