### PR TITLE
Updates for next major release

### PR DESCRIPTION
**Pull request by paf31**
- [x] Simplify instance contexts
- [x] Add `MonadRec ExceptT` instance (and others?)
- [x] `mtl` instances for `ExceptT`

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
I think this is ready to review. /cc @natefaubion

**Comment by natefaubion** [comment]
We also needed the mtl instances for ExceptT. We had them for ErrorT, but not ExceptT.

**Comment by paf31** [comment]
Ah good point, thanks.

**Comment by paf31** [comment]
We actually should release this together with 0.7.4 since neither's CI build will pass without the other.

**Comment by paf31** [comment]
I've added module exports too. This is ready for review again.

**Comment by garyb** [comment]
I'll probably have to review tomorrow morning now, just trying to solve something for SD before bed.

Pretty excited for these (and the accompanying typechecker) updates :smile:

**Comment by garyb** [comment]
Looks great! I made a PR #50 targeting this branch that further simplifies some of the contexts that can now depend on superclass implications.

**Pull request closed without merging**
