### PR TITLE
Codensity transformer (weaker than Continuation)

### PR DESCRIPTION
**Pull request by clinuxrulz**
With **CodensityT** you sacrifice *callcc*, but gain a **MonadRec** instance that can not be defined for **ContT**.

Something like this could be used to make a **Aff** with a **MonadRec** instance that does not rely on *later* with a magic stack depth (currently 100).

### CODE REVIEW

**Comment by paf31** [comment]
Interesting :smile: 

Is there an intuitive interpretation of the `MonadRec` instance?

**Comment by paf31** [comment]
I don't know if this is the same instance as for `Aff` actually. `makeAff` takes a function where `r` must be `Unit`, so I don't think `Codensity` is enough to model it.

**Comment by clinuxrulz** [comment]
Yeah, maybe not the actual "Aff", but something else similar to it.
I have no intuitive interpretation of the MonadRec instance. It was more fighting the type system until it type checks.

**Comment by clinuxrulz** [comment]
Apologies, you are correct. Defining Aff in terms of CodensityT is actually not possible. I got a bit excited after defining MonadRec for CodensityT and thought that ment a nice MonadRec instance for Aff.

When I tried the following

    newtype Aff eff a = Aff (ExceptT Error (CodensityT (Eff eff)) a)

I ended up with a *makeAff* of

    makeAff :: forall eff a. (forall r. (Error -> Eff eff r) -> (a -> Eff eff r) -> Eff eff r) -> Aff eff a
    makeAff f = Aff $ ExceptT $ CodensityT (\k ->
      f (\err -> k $ Left err) (\res -> k $ Right res)
    )

When ment that *f* in this *makeAff* could only be a blocking computation. (not useful for async).

**Comment by clinuxrulz** [comment]
Oh well.. one last selling point for **Codensity** is that you can turn left associated binds into right associated bind for the inner monad, which can improve performance for some monads.

See: https://github.com/raichoo/TheFreeAndTheFurious/blob/master/TheFreeAndTheFurious.pdf

It gives examples of improving performance for **Free** and **DList**s. Although purescript already has a good implementation of **Free**.

But because of the need of **MonadFree** for the *wrap* function. I think ***Codensity** does not really belong to *transformers* and probably needs to be in a package on its own.

**Pull request closed without merging**
