### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by paluh**
Backlinking to purescript/purescript#3942

### CODE REVIEW

**Comment by JordanMartinez** [comment]
CI is now failing due to two reasons:
- Foldable1 now includes `foldr1` and `foldl1`
- kind annotation compiler warnings

**Comment by JordanMartinez** [comment]
@paluh, I've fixed the kind annotations in this PR to your branch: https://github.com/paluh/purescript-transformers/pull/1

Please merge that when you get a chance. After its merged, the only thing blocking this PR is the `purescript-lazy` dependency. Its `Foldable1` instance for `Lazy` needs to be updated.

**Comment by paluh** [comment]
@JordanMartinez I'm not sure how I was able to don't notice these warnings. Sorry. You fix is included in this PR now.

**Comment by JordanMartinez** [comment]
This is blocked by `purescript-arrays` now due to using it as a test dependency.

**Review by JordanMartinez — APPROVED** [review]
CI now builds and I've verified that unicode syntax isn't being used here.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
