### PR TITLE
Added `monadErrorMaybe` instance

### PR DESCRIPTION
**Pull request by pseudonom**
If you all think the instance makes sense.

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
It's not law-abiding though, because of the `catch` implementation. Maybe restrict `e ~ Unit`?

**Comment by garyb** [comment]
Good point, I didn't think of that.

**Comment by pseudonom** [comment]
> not law-abiding

Yeah, it is sort of unusual behavior (though I don't see a clear statement of the laws anywhere). I do find it quite useful though (for combining with functions that return a `Maybe` or "choosing verbosity"):

```purescript
big ::  forall m a. (MonadError String m, Monad m) => Number -> m Number
big n | n < 0 = throwError "Negative"
         | n < 2 = throwError "Small"
         | otherwise = pure n

bigHead :: [Number] -> Maybe Number
bigHead = big <=< head
```

I guess the alternative is sprinkling something like `right :: Either a b -> Maybe b` around.

**Comment by jdegoes** [comment]
Yeah, the `Maybe` instance must be restricted to `Unit` if it exists at all.

**Comment by paf31** [comment]
I'm happy to merge this if we can change over to `Unit`.

**Comment by pseudonom** [comment]
Done. @paf31

**Comment by paf31** [comment]
Sorry, we need to fix `catchError` too.

**Comment by pseudonom** [comment]
Oh yeah.

**Comment by paf31** [comment]
Any chance you could rebase this please?

**Comment by pseudonom** [comment]
Done.

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
