### PR TITLE
Add ListT

### PR DESCRIPTION
**Pull request by paf31**
Not ready to merge yet, mostly because master is broken, but ready for review.

/cc @jdegoes @garyb

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1: 

I do want to revisit the laziness issue as I believe that can be cleaned up, but does require more thought and best done in a separate PR.

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
Yes, I think we can get laziness by just using the `Functor` instance on `f` when `f` has `Lazy` somewhere inside it. I tried that yesterday but couldn't quite figure it out. It would be nice to remove the dependency on `lazy` though.

**Comment by jdegoes** [comment]
> Yes, I think we can get laziness by just using the Functor instance on f when f has Lazy somewhere inside it. 

I would like requiring a Lazy type class on `f` to use the lazy cons functions, albeit the representation of ListT may have to change a bit which is why I haven't looked at it more. Advantage is: would be faster than current ListT (less wrapping).

**Pull request merged**
