### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by paf31**
Not done yet...

### CODE REVIEW

**Comment by paf31** [comment]
@garyb @joneshf Could you please review? Especially the (incomplete) laws?

Thanks.

**Comment by garyb** [comment]
Looks pretty good to me. It's a little unfortunate the order some of it comes out, as the the "whys" of the transformers is explained with the classes, but when reading straight through you tend to run into the non-transformer version of the monad first.

The laws look good so far too - I don't think I've ever seen them stated for the Haskell version. My only concern would be some of them aren't valid PS code I think, like `do { ask; ask }` - could we not use `ask *> ask` or something instead?

**Comment by paf31** [comment]
It might be better to just skip the laws, since they're not really "official" or anything, and certainly not comprehensive. I'm not sure.

It might be good if someone who knew what they were talking about could document the various comonad transformers too.

**Comment by paf31** [comment]
I broke up the docs a bit. I'll merge this, and spend a bit of time on the comonad modules. I've been doing a bit of reading today on comonads, and I think I can write something just comprehensible enough :)

**Pull request merged**
