### PR TITLE
Remove Semigroup constraint on monadRecErrorT

### PR DESCRIPTION
**Pull request by natefaubion**

### CODE REVIEW

**Comment by natefaubion** [comment]
The name for the instance is incorrect. Should I address that?

**Comment by paf31** [comment]
Yes please :) Also, we can remove the constraint from `ErrorT`'s `MonadRec` instance too.

**Comment by natefaubion** [comment]
Done

**Comment by paf31** [comment]
Hmm, minor bump or major bump? I think minor...

**Comment by garyb** [comment]
Yeah, minor I think. Dropping these constraints doesn't change the implications anywhere else.

**Comment by paf31** [comment]
I was thinking about the name change, but I think that's ok unless someone was using it from the FFI.

**Comment by garyb** [comment]
Ah ok, yeah.

**Pull request merged**
